### ISSUE TITLE
Bridgetown support?

### ISSUE THREAD

**Issue by joemasilotti** [alexmacarthur/jekyll-jam-comments#1]
I was recommended JamComments and it looks exactly like what I want. Privacy focused, no JavaScript, I own the data... the list goes on.

But my blog is built on [Bridgetown](https://www.bridgetownrb.com), a spiritual successor to Jekyll.

Is there any chance that Bridgetown support will be added in the future? If not, do you have any ideas on how I could integrate JamComments without using this gem?

Thanks in advance for any help!

**Comment by alexmacarthur** [comment]
Hi, @joemasilotti - thanks for asking. I've been hearing good things about Bridgetown and was sorta looking for an excuse to add an integration. Here's a first pass! Documentation isn't written out yet, but it's similar to Jekyll. Give a look and let me know what feedback you have in the meantime. 

Repo: https://github.com/alexmacarthur/bridgetown-jam-comments
Gem: https://rubygems.org/gems/bridgetown_jam_comments

**Comment by joemasilotti** [comment]
Thank you @alexmacarthur! I'll comment here when I give it a spin. Comments became a smaller priority for me right now but it is good to know this exists. :)
